#!/bin/bash
# Demo script for "deploy, break, heal with AI"

echo "=================================================="
echo "AI-ASSISTED KUBERNETES OPERATIONS DEMO"
echo "=================================================="
echo ""
echo "This demo showcases AI-assisted Kubernetes operations"
echo "including deployment, troubleshooting, and healing."
echo ""

echo "STEP 1: DEPLOY APPLICATION WITH AI ASSISTANCE"
echo "--------------------------------------------------"
echo "Using kubectl-ai to deploy the todo application..."
echo "kubectl-ai 'deploy helm chart todo-app from local directory'"
echo ""

echo "STEP 2: SIMULATE AN ISSUE"
echo "--------------------------------------------------"
echo "Simulating a pod failure scenario..."
echo "kubectl-ai 'scale backend deployment to 0 to simulate failure'"
echo ""

echo "STEP 3: AI-ASSISTED TROUBLESHOOTING"
echo "--------------------------------------------------"
echo "Using kagent to diagnose the issue..."
echo "kagent 'analyze why backend services are unavailable'"
echo ""

echo "STEP 4: AI-ASSISTED HEALING"
echo "--------------------------------------------------"
echo "Using kubectl-ai to fix the issue..."
echo "kubectl-ai 'scale backend deployment back to 1 replica'"
echo ""

echo "STEP 5: VALIDATE RESOLUTION"
echo "--------------------------------------------------"
echo "Confirming services are healthy again..."
echo "kubectl-ai 'show status of all deployments and services'"
echo ""

echo "=================================================="
echo "KEY BENEFITS DEMONSTRATED:"
echo "• Zero manual YAML creation"
echo "• Natural language Kubernetes operations"
echo "• AI-assisted troubleshooting"
echo "• Automated healing capabilities"
echo "• Continuous health monitoring"
echo "=================================================="